### PR TITLE
Interesting tests for paper

### PR DESCRIPTION
**Pull request by reilem**

### CODE REVIEW

**Review by gkaracha — CHANGES_REQUESTED** [review]
One thing that is not currently tested but we should have is an or-pattern where the left and the right overlap, and the left one is lazier than the right one (e.g. `Succ y || Succ Zero`). Then, you can try it on a `Succ (error "I shouldn't pop up")` and make sure that the error is not evaluated. Otherwise this PR LGTM :slightly_smiling_face:

**Comment by reilem** [comment]
I can add this test. Should I include it in the paper or just mention it?

**Comment by gkaracha** [comment]
> I can add this test. Should I include it in the paper or just mention it?

I'd definitely mention it. There should be at least one test illustrating the evaluation order for or-patterns and this is it.

**Comment by gkaracha** [comment]
About adding the code too; if there is space I'd say yes as well.

**Review by gkaracha — APPROVED** [review]
LGTM :+1: We could always add more tests later, but this is pretty OK as a starting point. Feel free to merge :slightly_smiling_face:

**Pull request merged**
